// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
// TEMPORALMENTE COMENTADO PARA RESOLVER CONFLICTOS DE iOS
/*
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Configuración para desarrollo - reemplazar con valores reales de Firebase
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw-1234567890abcdefghijklmnopqrstuvwxyz',
    appId: '1:123456789012:web:abcdefghijklmnopqrstuvwxyz',
    messagingSenderId: '123456789012',
    projectId: 'buffet-app-dev',
    authDomain: 'buffet-app-dev.firebaseapp.com',
    storageBucket: 'buffet-app-dev.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw-1234567890abcdefghijklmnopqrstuvwxyz',
    appId: '1:123456789012:android:abcdefghijklmnopqrstuvwxyz',
    messagingSenderId: '123456789012',
    projectId: 'buffet-app-dev',
    storageBucket: 'buffet-app-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBw-1234567890abcdefghijklmnopqrstuvwxyz',
    appId: '1:123456789012:ios:abcdefghijklmnopqrstuvwxyz',
    messagingSenderId: '123456789012',
    projectId: 'buffet-app-dev',
    storageBucket: 'buffet-app-dev.appspot.com',
    iosClientId: '123456789012-abcdefghijklmnopqrstuvwxyz.apps.googleusercontent.com',
    iosBundleId: 'com.buffetapp.pro.buffetApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBw-1234567890abcdefghijklmnopqrstuvwxyz',
    appId: '1:123456789012:macos:abcdefghijklmnopqrstuvwxyz',
    messagingSenderId: '123456789012',
    projectId: 'buffet-app-dev',
    storageBucket: 'buffet-app-dev.appspot.com',
    iosClientId: '123456789012-abcdefghijklmnopqrstuvwxyz.apps.googleusercontent.com',
    iosBundleId: 'com.buffetapp.pro.buffetApp',
  );
}
*/
